In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np

In [14]:
df=pd.read_csv('car-details.csv')
df

,name,company,model,edition,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
0,Maruti Swift Dzire VDI,Maruti,Swift,Dzire VDI,2014,First,Diesel,Individual,Manual,145500,55.00,1248.0,74.00,190.000000,5.0,450000
1,Skoda Rapid 1.5 TDI Ambition,Skoda,Rapid,1.5 TDI Ambition,2014,Second,Diesel,Individual,Manual,120000,49.70,1498.0,103.52,250.000000,5.0,370000
2,Honda City 2017-2020 EXi,Honda,City,2017-2020 EXi,2006,Third,Petrol,Individual,Manual,140000,41.60,1497.0,78.00,124.544455,5.0,158000
3,Hyundai i20 Sportz Diesel,Hyundai,i20,Sportz Diesel,2010,First,Diesel,Individual,Manual,127000,54.06,1396.0,90.00,219.668960,5.0,225000
4,Maruti Swift VXI BSIII,Maruti,Swift,VXI BSIII,2007,First,Petrol,Individual,Manual,120000,37.84,1298.0,88.20,112.776475,5.0,130000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6921,Maruti Wagon R VXI BS IV with ABS,Maruti,Wagon,R VXI BS IV with ABS,2013,Second,Petrol,Individual,Manual,50000,44.40,998.0,67.10,90.000000,5.0,260000
6922,Hyundai i20 Magna 1.4 CRDi,Hyundai,i20,Magna 1.4 CRDi,2014,Second,Diesel,Individual,Manual,80000,52.97,1396.0,88.73,219.700000,5.0,475000
6923,Hyundai i20 Magna,Hyundai,i20,Magna,2013,First,Petrol,Individual,Manual,110000,43.47,1197.0,82.85,113.700000,5.0,320000
6924,Hyundai Verna CRDi SX,Hyundai,Verna,CRDi SX,2007,Fourth & Above,Diesel,Individual,Manual,119000,39.47,1493.0,110.00,235.359600,5.0,135000
6925,Maruti Swift Dzire ZDi,Maruti,Swift,Dzire ZDi,2009,First,Diesel,Individual,Manual,120000,45.34,1248.0,73.90,190.000000,5.0,382000

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6926 entries, 0 to 6925
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6926 non-null   str
 1   company        6926 non-null   str
 2   model          6926 non-null   str
 3   edition        6926 non-null   str
 4   year           6926 non-null   int64
 5   owner          6926 non-null   str
 6   fuel           6926 non-null   str
 7   seller_type    6926 non-null   str
 8   transmission   6926 non-null   str
 9   km_driven      6926 non-null   int64
 10  mileage_mpg    6718 non-null   float64
 11  engine_cc      6718 non-null   float64
 12  max_power_bhp  6717 non-null   float64
 13  torque_nm      6717 non-null   float64
 14  seats          6718 non-null   float64
 15  selling_price  6926 non-null   int64
dtypes: float64(5), int64(3), str(8)
memory usage: 865.9 KB

In [16]:
df.isna().sum()

name               0
company            0
model              0
edition            0
year               0
owner              0
fuel               0
seller_type        0
transmission       0
km_driven          0
mileage_mpg      208
engine_cc        208
max_power_bhp    209
torque_nm        209
seats            208
selling_price      0
dtype: int64

In [17]:
df.shape

(6926, 16)

In [11]:
for col in df.select_dtypes(include='O').columns:
    print(f'Column:{col}')
    print(f'Cardinality:{df[col].nunique()}')
    print(df[col].unique())
    print(df[col].value_counts(normalize=True))
    print()

Column:company
Cardinality:32
<StringArray>
[       'Maruti',         'Skoda',         'Honda',       'Hyundai',
        'Toyota',          'Ford',       'Renault',      'Mahindra',
          'Tata',     'Chevrolet',          'Fiat',        'Datsun',
          'Jeep', 'Mercedes-Benz',    'Mitsubishi',          'Audi',
    'Volkswagen',           'BMW',        'Nissan',         'Lexus',
        'Jaguar',          'Land',            'MG',         'Volvo',
        'Daewoo',           'Kia',         'Force',    'Ambassador',
         'Ashok',         'Isuzu',          'Opel',       'Peugeot']
Length: 32, dtype: str
company
Maruti           0.312590
Hyundai          0.182934
Mahindra         0.104389
Tata             0.093416
Honda            0.052267
Ford             0.052122
Toyota           0.051545
Chevrolet        0.031187
Renault          0.029743
Volkswagen       0.025123
Nissan           0.010540
Skoda            0.010107
Datsun           0.008230
BMW              0.006786
Mercedes-Benz    0.006642
Fiat             0.006353
Audi             0.004765
Jeep             0.003176
Mitsubishi       0.001588
Volvo            0.001299
Jaguar           0.001155
Force            0.000578
Ambassador       0.000578
Isuzu            0.000578
Land             0.000433
MG               0.000433
Daewoo           0.000433
Kia              0.000433
Lexus            0.000144
Ashok            0.000144
Opel             0.000144
Peugeot          0.000144
Name: proportion, dtype: float64

Column:owner
Cardinality:5
<StringArray>
['First', 'Second', 'Third', 'Fourth & Above', 'Test Drive Car']
Length: 5, dtype: str
owner
First             0.612475
Second            0.285013
Third             0.077390
Fourth & Above    0.024401
Test Drive Car    0.000722
Name: proportion, dtype: float64

Column:fuel
Cardinality:4
<StringArray>
['Diesel', 'Petrol', 'LPG', 'CNG']
Length: 4, dtype: str
fuel
Diesel    0.542160
Petrol    0.444268
CNG       0.008085
LPG       0.005487
Name: proportion, dtype: float64

Column:seller_type
Cardinality:3
<StringArray>
['Individual', 'Dealer', 'Trustmark Dealer']
Length: 3, dtype: str
seller_type
Individual          0.897776
Dealer              0.098325
Trustmark Dealer    0.003898
Name: proportion, dtype: float64

Column:transmission
Cardinality:2
<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str
transmission
Manual       0.91568
Automatic    0.08432
Name: proportion, dtype: float64

C:\Users\vishal.pandey\AppData\Local\Temp\ipykernel_3708\330079010.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='O').columns:

In [18]:
df=df.drop(columns=['name','model','edition'])
df.head()

,company,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
0,Maruti,2014,First,Diesel,Individual,Manual,145500,55.00,1248.0,74.00,190.000000,5.0,450000
1,Skoda,2014,Second,Diesel,Individual,Manual,120000,49.70,1498.0,103.52,250.000000,5.0,370000
2,Honda,2006,Third,Petrol,Individual,Manual,140000,41.60,1497.0,78.00,124.544455,5.0,158000
3,Hyundai,2010,First,Diesel,Individual,Manual,127000,54.06,1396.0,90.00,219.668960,5.0,225000
4,Maruti,2007,First,Petrol,Individual,Manual,120000,37.84,1298.0,88.20,112.776475,5.0,130000

In [21]:
df=df.drop_duplicates()
df.head()

,company,year,owner,fuel,seller_type,transmission,km_driven,mileage_mpg,engine_cc,max_power_bhp,torque_nm,seats,selling_price
0,Maruti,2014,First,Diesel,Individual,Manual,145500,55.00,1248.0,74.00,190.000000,5.0,450000
1,Skoda,2014,Second,Diesel,Individual,Manual,120000,49.70,1498.0,103.52,250.000000,5.0,370000
2,Honda,2006,Third,Petrol,Individual,Manual,140000,41.60,1497.0,78.00,124.544455,5.0,158000
3,Hyundai,2010,First,Diesel,Individual,Manual,127000,54.06,1396.0,90.00,219.668960,5.0,225000
4,Maruti,2007,First,Petrol,Individual,Manual,120000,37.84,1298.0,88.20,112.776475,5.0,130000

In [22]:
df.duplicated().sum()

np.int64(0)

In [24]:
x=df.drop(columns='selling_price')
y=df.selling_price.copy()
print(x.shape,y.shape)

(6907, 12) (6907,)

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(5525, 12) (1382, 12)
(5525,) (1382,)

In [33]:
num_cols=x_train.select_dtypes(include='number').columns.tolist()
cat_cols=[col for col in x_train.columns if col not in num_cols]
print(num_cols)
print(cat_cols)

['year', 'km_driven', 'mileage_mpg', 'engine_cc', 'max_power_bhp', 'torque_nm', 'seats']
['company', 'owner', 'fuel', 'seller_type', 'transmission']

In [42]:
num_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', num_pipe, num_cols),
    ('cat', cat_pipe, cat_cols)
])

regressor = RandomForestRegressor(
    n_estimators=10,
    max_depth=5,
    random_state=42
)

rf_model = Pipeline(steps=[
    ('pre', preprocessor),
    ('reg', regressor)
])

rf_model.fit(x_train, y_train)

Pipeline(steps=[('pre',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['year', 'km_driven',
                                                   'mileage_mpg', 'engine_cc',
                                                   'max_power_bhp', 'torque_nm',
                                                   'seats']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['company', 'owner', 'fuel',
                                                   'seller_type',
                                                   'transmission'])])),
                ('reg',
                 RandomForestRegressor(max_depth=5, n_estimators=10,
                                       random_state=42))])

In [47]:
y_train_pred = rf_model.predict(x_train)

train_mse = mean_squared_error(y_train, y_train_pred)
train_rmse = np.sqrt(train_mse)

print(f"Train RMSE: {train_rmse:.3f}")

y_test_pred = rf_model.predict(x_test)

test_mse = mean_squared_error(y_test, y_test_pred)
test_rmse = np.sqrt(test_mse)

print(f"Test RMSE: {test_rmse:.3f}")

Train RMSE: 169947.490
Test RMSE: 172392.131